PROTON_COMMIT := 7bbaf3c22f37e9c9db5fc7982483bc0a6bd6a050
.PHONY: clean genclient genspec

genclient: clean genspec ## Generate the client using openapi-generator
	@openapi-generator generate -g python -o "." \
	-i "./etc/openapi.json" -c ./etc/openapi.conf.yaml \
	--git-user-id raystack \
    --git-repo-id "shield-python" \
    --git-host github.com
	@rm -f .gitlab-ci.yml .travis.yml
	@echo " > client generated"

clean:
	@cat .openapi-generator/FILES | grep -v etc | grep -v .openapi-generator-ignore | \
	 grep -v api_example.py | grep -v Makefile | grep -v README.md | grep -v example | \
	 grep -v pyproject.toml | \
	 xargs rm -rf
	@rm -rf test __pycache__ docs shield_api
	@echo " > autogenerated files deleted"

genspec: ## Generate the openapi v3 spec using raystack/shield generated v2 spec
	@echo " > generating openapiv3 spec"
	@curl -X 'GET' \
  'https://converter.swagger.io/api/convert?url=https%3A%2F%2Fraw.githubusercontent.com%2Fraystack%2Fshield%2F${PROTON_COMMIT}%2Fproto%2Fapidocs.swagger.yaml' \
  -H 'accept: application/json' > ./etc/openapi.json
