# coding: utf-8

"""
    Frontier Administration API

    The Frontier APIs adhere to the OpenAPI specification, also known as Swagger, which provides a standardized approach for designing, documenting, and consuming RESTful APIs. With OpenAPI, you gain a clear understanding of the API endpoints, request/response structures, and authentication mechanisms supported by the Frontier APIs. By leveraging the OpenAPI specification, developers can easily explore and interact with the Frontier APIs using a variety of tools and libraries. The OpenAPI specification enables automatic code generation, interactive API documentation, and seamless integration with API testing frameworks, making it easier than ever to integrate Frontier into your existing applications and workflows.  # noqa: E501

    The version of the OpenAPI document: 0.2.0
    Contact: hello@raystack.org
    Generated by: https://openapi-generator.tech
"""

from frontier_api.paths.v1beta1_admin_projects.get import AdminServiceListProjects
from frontier_api.paths.v1beta1_projects.post import FrontierServiceCreateProject
from frontier_api.paths.v1beta1_projects_id.delete import FrontierServiceDeleteProject
from frontier_api.paths.v1beta1_projects_id_disable.post import FrontierServiceDisableProject
from frontier_api.paths.v1beta1_projects_id_enable.post import FrontierServiceEnableProject
from frontier_api.paths.v1beta1_projects_id.get import FrontierServiceGetProject
from frontier_api.paths.v1beta1_projects_id_admins.get import FrontierServiceListProjectAdmins
from frontier_api.paths.v1beta1_projects_id_serviceusers.get import FrontierServiceListProjectServiceUsers
from frontier_api.paths.v1beta1_projects_id_users.get import FrontierServiceListProjectUsers
from frontier_api.paths.v1beta1_projects_id.put import FrontierServiceUpdateProject


class ProjectApi(
    AdminServiceListProjects,
    FrontierServiceCreateProject,
    FrontierServiceDeleteProject,
    FrontierServiceDisableProject,
    FrontierServiceEnableProject,
    FrontierServiceGetProject,
    FrontierServiceListProjectAdmins,
    FrontierServiceListProjectServiceUsers,
    FrontierServiceListProjectUsers,
    FrontierServiceUpdateProject,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
