# coding: utf-8

"""
    Shield Administration API

    The Shield APIs adhere to the OpenAPI specification, also known as Swagger, which provides a standardized approach for designing, documenting, and consuming RESTful APIs. With OpenAPI, you gain a clear understanding of the API endpoints, request/response structures, and authentication mechanisms supported by the Shield APIs. By leveraging the OpenAPI specification, developers can easily explore and interact with the Shield APIs using a variety of tools and libraries. The OpenAPI specification enables automatic code generation, interactive API documentation, and seamless integration with API testing frameworks, making it easier than ever to integrate Shield into your existing applications and workflows.  # noqa: E501

    The version of the OpenAPI document: 0.2.0
    Contact: hello@raystack.org
    Generated by: https://openapi-generator.tech
"""

from shield_api.paths.v1beta1_policies.get import AdminServiceListPolicies
from shield_api.paths.v1beta1_policies.post import ShieldServiceCreatePolicy
from shield_api.paths.v1beta1_policies_id.delete import ShieldServiceDeletePolicy
from shield_api.paths.v1beta1_policies_id.get import ShieldServiceGetPolicy
from shield_api.paths.v1beta1_policies_id.put import ShieldServiceUpdatePolicy


class PolicyApi(
    AdminServiceListPolicies,
    ShieldServiceCreatePolicy,
    ShieldServiceDeletePolicy,
    ShieldServiceGetPolicy,
    ShieldServiceUpdatePolicy,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
