# coding: utf-8

"""
    Shield Administration API

    The Shield APIs adhere to the OpenAPI specification, also known as Swagger, which provides a standardized approach for designing, documenting, and consuming RESTful APIs. With OpenAPI, you gain a clear understanding of the API endpoints, request/response structures, and authentication mechanisms supported by the Shield APIs. By leveraging the OpenAPI specification, developers can easily explore and interact with the Shield APIs using a variety of tools and libraries. The OpenAPI specification enables automatic code generation, interactive API documentation, and seamless integration with API testing frameworks, making it easier than ever to integrate Shield into your existing applications and workflows.  # noqa: E501

    The version of the OpenAPI document: 0.2.0
    Contact: hello@raystack.org
    Generated by: https://openapi-generator.tech
"""

from shield_api.paths.v1beta1_admin_projects.get import AdminServiceListProjects
from shield_api.paths.v1beta1_projects.post import ShieldServiceCreateProject
from shield_api.paths.v1beta1_projects_id.delete import ShieldServiceDeleteProject
from shield_api.paths.v1beta1_projects_id_disable.post import ShieldServiceDisableProject
from shield_api.paths.v1beta1_projects_id_enable.post import ShieldServiceEnableProject
from shield_api.paths.v1beta1_projects_id.get import ShieldServiceGetProject
from shield_api.paths.v1beta1_projects_id_admins.get import ShieldServiceListProjectAdmins
from shield_api.paths.v1beta1_projects_id_users.get import ShieldServiceListProjectUsers
from shield_api.paths.v1beta1_projects_id.put import ShieldServiceUpdateProject


class ProjectApi(
    AdminServiceListProjects,
    ShieldServiceCreateProject,
    ShieldServiceDeleteProject,
    ShieldServiceDisableProject,
    ShieldServiceEnableProject,
    ShieldServiceGetProject,
    ShieldServiceListProjectAdmins,
    ShieldServiceListProjectUsers,
    ShieldServiceUpdateProject,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
