# coding: utf-8

"""
    Shield Administration API

    The Shield APIs adhere to the OpenAPI specification, also known as Swagger, which provides a standardized approach for designing, documenting, and consuming RESTful APIs. With OpenAPI, you gain a clear understanding of the API endpoints, request/response structures, and authentication mechanisms supported by the Shield APIs. By leveraging the OpenAPI specification, developers can easily explore and interact with the Shield APIs using a variety of tools and libraries. The OpenAPI specification enables automatic code generation, interactive API documentation, and seamless integration with API testing frameworks, making it easier than ever to integrate Shield into your existing applications and workflows.  # noqa: E501

    The version of the OpenAPI document: 0.2.0
    Contact: hello@raystack.org
    Generated by: https://openapi-generator.tech
"""

from shield_api.paths.v1beta1_admin_resources.get import AdminServiceListResources
from shield_api.paths.v1beta1_projects_project_id_resources.post import ShieldServiceCreateProjectResource
from shield_api.paths.v1beta1_projects_project_id_resources_id.delete import ShieldServiceDeleteProjectResource
from shield_api.paths.v1beta1_projects_project_id_resources_id.get import ShieldServiceGetProjectResource
from shield_api.paths.v1beta1_projects_project_id_resources.get import ShieldServiceListProjectResources
from shield_api.paths.v1beta1_projects_project_id_resources_id.put import ShieldServiceUpdateProjectResource


class ResourceApi(
    AdminServiceListResources,
    ShieldServiceCreateProjectResource,
    ShieldServiceDeleteProjectResource,
    ShieldServiceGetProjectResource,
    ShieldServiceListProjectResources,
    ShieldServiceUpdateProjectResource,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
