# coding: utf-8

# flake8: noqa

"""
    Frontier Administration API

    The Frontier APIs adhere to the OpenAPI specification, also known as Swagger, which provides a standardized approach for designing, documenting, and consuming RESTful APIs. With OpenAPI, you gain a clear understanding of the API endpoints, request/response structures, and authentication mechanisms supported by the Frontier APIs. By leveraging the OpenAPI specification, developers can easily explore and interact with the Frontier APIs using a variety of tools and libraries. The OpenAPI specification enables automatic code generation, interactive API documentation, and seamless integration with API testing frameworks, making it easier than ever to integrate Frontier into your existing applications and workflows.  # noqa: E501

    The version of the OpenAPI document: 0.2.0
    Contact: hello@raystack.org
    Generated by: https://openapi-generator.tech
"""

__version__ = "1.0.0"

# import ApiClient
from frontier_api.api_client import ApiClient

# import Configuration
from frontier_api.configuration import Configuration

# import exceptions
from frontier_api.exceptions import OpenApiException
from frontier_api.exceptions import ApiAttributeError
from frontier_api.exceptions import ApiTypeError
from frontier_api.exceptions import ApiValueError
from frontier_api.exceptions import ApiKeyError
from frontier_api.exceptions import ApiException
